### ISSUE TITLE
P2Pool hardfork to-do list

### ISSUE THREAD

**Issue by SChernykh** [SChernykh/p2pool#224]
- [x] Announce hardfork plans on Reddit/IRC/p2pool.io/p2pool.observer
- [x] Implement automatic PPLNS window to reduce Monero blockchain bloat #221
- [x] Fix duplicate shares #222
- [x] Implement new tx key generation algorithm #223
- [x] Randomize output order for P2Pool payouts #225
- [x] Set hardfork date to **2023-03-18 21:00 UTC** 
- [x] Perform testing on testnet #228 
- [x] Release **P2Pool v3.0 binaries: 2023-01-31**
- [x] Announce new release and hardfork on Reddit/IRC/p2pool.io/p2pool.observer
- [x] Make a pull request to [Monero GUI](https://github.com/monero-project/monero-gui/) to update it to P2Pool v3.0
- [x] Push for new [Monero GUI](https://github.com/monero-project/monero-gui/) release before March
- [x] Push for new [Gupax](https://github.com/hinto-janaiyo/gupax) release before March
- [x] Release P2Pool v3.1 binaries with potential fixes and updates (consensus compatible with v3.0): 2023-02-28
